name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install musl tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build binary
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Prepare release assets
        run: |
          mkdir -p release
          cp target/x86_64-unknown-linux-musl/release/iotd release/iotd-linux-x86_64
          chmod +x release/iotd-linux-x86_64
          cd release
          tar -czf iotd-linux-x86_64.tar.gz iotd-linux-x86_64
          sha256sum iotd-linux-x86_64.tar.gz > iotd-linux-x86_64.tar.gz.sha256
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            release/iotd-linux-x86_64.tar.gz
            release/iotd-linux-x86_64.tar.gz.sha256